### ISSUE TITLE
Problem : Test failing on production

### ISSUE THREAD

**Issue by MadanBhandari** [EmurgoHK/cardanoupdate#106]
Problem : Test failing on production since PR #104 

More details is on [Travis CI](https://travis-ci.org/EmurgoHK/cardanoupdate)

ping @gazhayes @anbud

**Comment by samuelralak** [comment]
cleared cache and restarted build. should be alright now

**Comment by MadanBhandari** [comment]
Yeah, just got email from Travis CI :)
