### ISSUE TITLE
problem: side menu is annoying on small screens

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/cardanoupdate#110]
problem: the side menu is annoying on small screens because it doesn't automatically close when tapping on the content.

solution: when on a small screen, close menu automatically when content (or whatever) is clicked.

**Comment by samuelralak** [comment]
I implemented a solution to this on blockrazor. whoever may take this might
consider checking it out or having something similar:)

**Comment by yujin718** [comment]
where did you implement as i'm new on this project?

**Comment by samuelralak** [comment]
checkout this commit [here](https://github.com/Blockrazor/blockrazor/commit/c2d20a8d524976b0382b2bd7fa02d6397dda8e8e)

**Comment by yujin718** [comment]
Ok. thanks.

**Comment by yujin718** [comment]
@emurgobot done

**Comment by gazhayes** [comment]
Hi @yujin718 are you going to send a pull request for this one?

**Comment by yujin718** [comment]
Yes. I'm new member and first pull request is my first scope

**Comment by samuelralak** [comment]
not at all. checking it out.

@emurgobot claim

**Comment by yujin718** [comment]
Please let me know what is issue from my commit? so i can know reason

**Comment by samuelralak** [comment]
Hi @yujin718 I took a look at your PR #135 and your patch didn't work because of the following:
- your if statement checks for class `nav-link` on the body, html element; this will always be false as body will never have a `nav-link` class, beside the `if` statement was totally unnecessary

**Comment by samuelralak** [comment]
@emurgobot done

done in #161
