### ISSUE TITLE
problem: no logo

### ISSUE THREAD

**Issue by kriswormwood** [EmurgoHK/cardanoupdate#112]
problem: no logo

solution: use this one. (transparent png)
![cardano logo3-01](https://user-images.githubusercontent.com/26383314/46657919-03b55e80-cbe4-11e8-9391-104d8069c8ad.png)

**Comment by MadanBhandari** [comment]
@emurgobot claim

**Comment by MadanBhandari** [comment]
Done in #124 
@emurgobot done
