### ISSUE TITLE
problem: new items are unfairly rated

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/cardanoupdate#116]
problem: new items are unfairly rated

solution: give each new item a score of 2 upvotes and 0 downvotes on creation so that they appear right at the top but then trend downwards immediately if the first vote is a downvote.

**Comment by samuelralak** [comment]
Where do the 2 upvotes come from?

**Comment by samuelralak** [comment]
1. vote from System
2. vote from Creator? 😄

**Comment by samuelralak** [comment]
@emurgobot claim

**Comment by gazhayes** [comment]
Whatever is easier I guess, it doesn't *really* matter.

**Comment by samuelralak** [comment]
@emurgobot done 

done in #121
