### ISSUE TITLE
problem: styling on news and projects is different

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/cardanoupdate#119]
problem: styling on news and projects is different

solution: use the same header on all pages (people arriving from Google could land anywhere and it won't be clear what this site is for)

**Comment by samuelralak** [comment]
@gazhayes just to be clear, the header should be applied on ALL pages NOT JUST the news list and project list pages?

**Comment by gazhayes** [comment]
Hmmmmm.... I'm not really sure to be honest. What do you think?

**Comment by samuelralak** [comment]
I would suggest that we only apply the same header to news and projects list since either can serve as home pages. We can leave other pages as is or apply something different (still yet to figure this out) unique to each page.

**Comment by gazhayes** [comment]
Yeah cool, that solves the problem anyway

**Comment by MadanBhandari** [comment]
@emurgobot claim
