### ISSUE TITLE
Problem: easy to forget to add RSVP info to events

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/cardanoupdate#132]
Problem: easy to forget to add RSVP info to events

solution: add an "RSVP instructions" field to the new event creation form

**Comment by IsmailMellouli** [comment]
@emurgobot claim

**Comment by IsmailMellouli** [comment]
@emurgobot label "done"

**Comment by MadanBhandari** [comment]
@IsmailMellouli Update issue with PR number and  `@emurgobot done`, no need to add label `done`. This will be automatically added by `@emurgobot done`
