### ISSUE TITLE
problem: github icon alignment is a bit off

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/cardanoupdate#133]
problem: github icon alignment is a bit off

**Comment by MadanBhandari** [comment]
@gazhayes I didn't understand this problem, which icon you are talking about here ? On Navigation or in Projects ?

**Comment by MadanBhandari** [comment]
@emurgobot lable "UI-UX"

**Comment by gazhayes** [comment]
Oh sorry, I mean the one in the top navbar

**Comment by MadanBhandari** [comment]
@emurgobot claim

**Comment by MadanBhandari** [comment]
Done in #140 
@emurgobot done
