### ISSUE TITLE
problem: users might miss sections on mobile

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/cardanoupdate#134]
problem: on desktop there are categories in the top menu bar but on mobile it's too small to display this and users might miss the other sections

solution: on mobile, replace the tagline in the header with links to news projects and evente pages.

**Comment by MadanBhandari** [comment]
@emurgobot lable "UI-UX"
@emurgobot claim

**Comment by MadanBhandari** [comment]
Done in #139 
@emurgobot done
