### ISSUE TITLE
Problem : Projects description can't be formatted

### ISSUE THREAD

**Issue by MadanBhandari** [EmurgoHK/cardanoupdate#141]
Problem : Projects description can't be formatted

Solution : Add markdown editor like in events and news

**Comment by MadanBhandari** [comment]
@emurgobot claim

**Comment by samuelralak** [comment]
Hey @MadanBhandari take a look at this issue here [#19](https://github.com/EmurgoHK/cardanoupdate/issues/19)

**Comment by MadanBhandari** [comment]
@samuelralak Thanks for the heads-up, closing this issue as this is not a requirement.
