### ISSUE TITLE
Problem : User can't reset password

### ISSUE THREAD

**Issue by MadanBhandari** [EmurgoHK/cardanoupdate#145]
Problem : User can't reset password

Solution : Add password reset form

@gazhayes do we have email details or should I create new account on SendGrid like we did on `blockrazor` ?

**Comment by MadanBhandari** [comment]
@emurgobot claim

**Comment by gazhayes** [comment]
Hmmm, just create a new account

**Comment by MadanBhandari** [comment]
Done in #155 

@emurgobot done
