### ISSUE TITLE
problem: can't see user statistics

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/cardanoupdate#146]
problem: can't see user statistics

solution: show number of total users and number of online users. Blockrazor is already doing this so some code could be stolen from there.

**Comment by yujin718** [comment]
@emurgobot claim

**Comment by yujin718** [comment]
Hello which page you mean?

**Comment by yujin718** [comment]
@emurgobot abandon

**Comment by MadanBhandari** [comment]
@emurgobot claim

**Comment by gazhayes** [comment]
ping @MadanBhandari how you going on this one?

**Comment by MadanBhandari** [comment]
I am sending PR in a bit.
