### ISSUE TITLE
problem: cannot add academic papers

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/cardanoupdate#148]
problem: IOHK funds cryptography research at a variety of universities globally but these papers cannot be added to the site.

solution: add a "research" section. Allow users to add a headline, abstract, and upload a PDF.

**Comment by anbud** [comment]
@emurgobot claim

**Comment by anbud** [comment]
@gazhayes, what upload directory should I use here? `/home/gareth/cardanoupdate_assets/static/pdfs/`?

**Comment by anbud** [comment]
Done in #156.

@emurgobot done
