### ISSUE TITLE
problem: logo spacing is off

### ISSUE THREAD

**Issue by kriswormwood** [EmurgoHK/cardanoupdate#149]
problem: logo spacing is off

solution: corrected logo spacing uploaded here. replace. 
![cardano logo update4](https://user-images.githubusercontent.com/26383314/46717292-f6f34200-cc99-11e8-873e-ba5560bf4772.png)

**Comment by MadanBhandari** [comment]
Just replacing logo image should fix the issue.

**Comment by MadanBhandari** [comment]
@emurgobot claim

**Comment by MadanBhandari** [comment]
Done in #152 
@emurgobot done
