### ISSUE TITLE
problem: there is no edit button on the post

### ISSUE THREAD

**Issue by kriswormwood** [EmurgoHK/cardanoupdate#150]
problem: there is no edit button on the post once it is submitted and viewed.

solution: add edit link for poster to revise and edit post.

**Comment by MadanBhandari** [comment]
Currently edit and delete options only are available in `/projects`, `/events` and `/home`. Users can see settings icon on top right of each card if that post is created by him/herself.

Or are you suggesting we should add edit button inside the post itself as well ?

**Comment by gazhayes** [comment]
Should probably add it inside the post (or whatever) too

**Comment by MadanBhandari** [comment]
Done in #154 
@emurgobot done
