### ISSUE TITLE
problem: error when uploading research papers

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/cardanoupdate#158]
problem: error when uploading research papers: failed to validate md5 hash

ping @anbud

**Comment by anbud** [comment]
I'll check it out, I haven't seen this error locally.

@emurgobot claim

**Comment by anbud** [comment]
This was actually happening only on certain pdf files that had a dangling empty newline at the end of the document. Trimming data fixes the problem.

Fixed in #162.

@emurgobot done
