### ISSUE TITLE
Problem: home route only shows news

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/cardanoupdate#160]
Problem: the home route only shows news items. 

Solution: put news on its *own* route (/news I guess). On the *home* route (/), add everything (news, events, projects) and sort by most recent.

**Comment by MadanBhandari** [comment]
Earlier, I tried to cover this on #82, looks like it's completely changed.

What I suggest is list most recent news items (let's say 10) and provide view all link to all news OR list all of the post once at including projects, events, research papers and give them tag (or category like news, project, event etc.)

**Comment by gazhayes** [comment]
I think the tag idea is best, just because it's more flexible and probably the simplest solution. What do you think?

**Comment by MadanBhandari** [comment]
Yes, that's good option though but we need same layout for all posts.

@gazhayes My reference for Option 1 is [this one](https://tympanus.net/codrops/). Check this and let me know what you think about similar approach.

**Comment by gazhayes** [comment]
It's up to you really, we can always change it later if it doesn't work out. Have fun!

**Comment by MadanBhandari** [comment]
I won't change current `news` layout  and this will moved to `/news`.

I am gonna explore both the options and will keep updating here, completing this issue will take little more time than usual.

@emurgobot claim

**Comment by gazhayes** [comment]
ping @MadanBhandari

**Comment by MadanBhandari** [comment]
I was travelling to my home town in Nepal from India and air travel is not an option for me :D

I won't hold any issue this much long in future :)

Done in #182 
@emurgobot done
