### ISSUE TITLE
problem: picture insert button inserts http link

### ISSUE THREAD

**Issue by kriswormwood** [EmurgoHK/cardanoupdate#169]
problem: picture insert button inserts http link

**Comment by gazhayes** [comment]
Where on the site did this happen?

**Comment by kriswormwood** [comment]
add news

**Comment by kriswormwood** [comment]
<img width="586" alt="screen shot 2018-10-12 at 3 54 27 pm" src="https://user-images.githubusercontent.com/26383314/46855748-212e3680-ce37-11e8-98bd-723daf9e26b7.png">

**Comment by anbud** [comment]
Yap, this is intended behavior of the markdown editor. But, I can make a custom insert image button in the toolbar, of course, which will show an image upload form (probably in a modal) and insert the uploaded image. Is that what you had in mind? :)

@emurgobot claim

**Comment by gazhayes** [comment]
I'd say that will do the trick

**Comment by anbud** [comment]
Done in #176.

@emurgobot done
