### ISSUE TITLE
problem: contributors miscatagorize things

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/cardanoupdate#171]
problem: contributors sometimes miscatagorize things in the projects section.

solution: add guidance for contributors when they first start adding projects to the site. It's probably simplest to just launch a modal when users go to add an item and allow them to either `close` (default) or `don't show again`.

When adding a project:
`Projects added here must be something that people can use with Cardano, for example a wallet, a developer library, a development framework, etc.`

project description (onFocus):
`Please provide a very clear description of what the project is for, what it does, or what problem it solves.`

**Comment by samuelralak** [comment]
@emurgobot claim

**Comment by gazhayes** [comment]
ping @samuelralak how you going with this one?

**Comment by samuelralak** [comment]
next PR chief

**Comment by samuelralak** [comment]
abandoning this issue so that someone else can claim it. may not have time for at least the next 2 days

@emurgobot abandon

**Comment by MadanBhandari** [comment]
@emurgobot claim

**Comment by MadanBhandari** [comment]
Done in #187 
@emurgobot done
