### ISSUE TITLE
problem: logo crop incorrect

### ISSUE THREAD

**Issue by kriswormwood** [EmurgoHK/cardanoupdate#177]
problem: logo crop incorrect

solution: this logo is revised for mobile and desks (minimal edge)

![cardano logo update6](https://user-images.githubusercontent.com/26383314/46939819-d6602900-d099-11e8-9893-6c7999db38cd.png)

**Comment by MadanBhandari** [comment]
@emurgobot claim

**Comment by MadanBhandari** [comment]
Done in #179 
@emurgobot done
