### ISSUE TITLE
Problem : Events are not labelled 

### ISSUE THREAD

**Issue by MadanBhandari** [EmurgoHK/cardanoupdate#183]
Problem : Events are not labelled as per status

Solution : Add labels as per event start and end date like, upcoming, ongoing and closed (or over), and on home page only show upcoming and ongoing events only

**Comment by gazhayes** [comment]
This could be done just by using the date/time instead of creating an extra label couldn't it?

**Comment by MadanBhandari** [comment]
Yes, there won't be any extra field, that would be automatic label based on date, just to show upcoming or ongoing events, displaying passed events on home page doesn't make sense.

**Comment by MadanBhandari** [comment]
@emurgobot claim

**Comment by MadanBhandari** [comment]
Done in #185 
@emurgobot done
