### ISSUE TITLE
problem: news section isn't actually very useful

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/cardanoupdate#186]
problem: after a bit of experimentation and consultation with the cardano community, it appears that people don't actually care about the news section, and people can easily get updated from reddit or something. The feedback I've received from various parties indicates that it's best to make the site focused on projects, events, etc .

solution:
Eradicate the news section entirely. Update the home route to show everything else instead.

**Comment by MadanBhandari** [comment]
@emurgobot done in #199
