### ISSUE TITLE
problem: cannot add cardano related projects

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/cardanoupdate#19]
problem: there are a number of new cardano related projects popping up all the time from IOHK, Emurgo, and the community in general. There's no definitive list of these projects.

solution: allow users to add projects and display these separately to news items. Projects require a headline (maybe 100 chars), a short description (no markdown etc), and a link.

**Comment by samuelralak** [comment]
@emurgobot claim

**Comment by gazhayes** [comment]
@samuelralak how you going with this one?

**Comment by samuelralak** [comment]
next PR chief
