### ISSUE TITLE
problem: projects built on cardano not considered

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/cardanoupdate#191]
problem: there's a difference between projects that are *for* cardano, and projects that are built *on* cardano or *use* cardano. For example, a wallet is something that is built *for* cardano. However a new token that simply uses the cardano blockchain as a host is something build *on* cardano. This is not currently taken into consideration.

solution: when users add a project, ask them if this is something *for* cardano, or if it's something that's built *on top* of cardano.

The best way to do this is probably a radio button (or maybe something more UI friendly) which is mandatory. An explanation should be provided:

`Is this project something *for* Cardano OR something built *on* Cardano? An example of something that's *for* Cardano is a wallet or a developer library. An example of something built *on* Cardano is Traxia.`

The simplest way to deal with the data provided by the users is probably to just add a tag to the existing tags: built-on-cardano and built-for-cardano

**Comment by anbud** [comment]
@emurgobot claim

**Comment by anbud** [comment]
Done in #198.

@emurgobot done
