### ISSUE TITLE
github is acting weird today

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/cardanoupdate#204]
github is having major global problems today, comments, pull request, etc are being reset all the time. Hopefully this message actually gets through to everyone's email.

ping @anbud @geekyd @AshHimself @samuelralak @omar20261

**Comment by samuelralak** [comment]
yep. felt it here as well. seems to be working on my end now

**Comment by anbud** [comment]
Everything seems to be working now on my end as well. :)

**Comment by geekyd** [comment]
Yeah. I felt it as well. It seems like its working now :)

**Comment by gazhayes** [comment]
https://twitter.com/CardanoGaz/status/1054313457875472384
