### ISSUE TITLE
Problem: User can create multiple projects with same name

### ISSUE THREAD

**Issue by geekyd** [EmurgoHK/cardanoupdate#208]
Problem: User can create multiple projects with same name

Solution: User should not be able to add multiple projects with same name

**Comment by geekyd** [comment]
@emurgobot claim

**Comment by anbud** [comment]
Isn't it better for SEO purposes to use the slug/name instead of a random id in the URL? :)

**Comment by geekyd** [comment]
@anbud Yeah it definitely is better to use a name/slug for better SEO. But this can also cause problems with same slugs. 
One workaround would be to add a slug like `NAME-ID`

**Comment by geekyd** [comment]
I will change the issue to `User can create multiple projects with same name` & use the second solution :)

@anbud Thanks :)

**Comment by anbud** [comment]
Hmm, the friendly-slugs package we're using automatically appends -1, -2, etc if the name already exists. We could use name-id, that would work as well. :)

**Comment by geekyd** [comment]
Just tested friendly-slugs. As stated by Andrej above it automatically handles this situation therefore this will not be required. 

Closing this
