### ISSUE TITLE
Problem: Unable to create projects in project

### ISSUE THREAD

**Issue by geekyd** [EmurgoHK/cardanoupdate#209]
Problem: Unable to create projects in project this happened after https://github.com/EmurgoHK/cardanoupdate/pull/197

Tags, build for/on cardano & the project creation is not working.
![screenshot 2018-10-23 at 12 37 07 am](https://user-images.githubusercontent.com/12807846/47313135-cb8a3300-d65b-11e8-8334-2be8f50d931e.png)

Solution: Revert #197 

Ping @anbud @gazhayes @samuelralak

**Comment by gazhayes** [comment]
If the simplest solution (least code changes) to fix this are to revert #197 then feel free to go ahead and send a PR that reverts it. If the simplest solution is something else, that's also ok.

**Comment by gazhayes** [comment]
Fixed in #210
