### ISSUE TITLE
problem: no Learn section

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/cardanoupdate#217]
problem: there are a lot of resources available for people to learn how to use cardano or learn about different aspects of cardano, but there's no scope for this on the site.

solution:
add a `Learn` section: 

Title: 25 chars max, hint: What are users going to learn about by reading or watching this?

Content: 5000 chars max

Tags

**Comment by anbud** [comment]
@emurgobot claim

**Comment by anbud** [comment]
Done in #232.

@emurgobot done
