### ISSUE TITLE
problem: user stats boxes are too big

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/cardanoupdate#220]
Problem and possible solution:
<img width="710" alt="screenshot 2018-10-23 at 6 57 07 pm" src="https://user-images.githubusercontent.com/8143945/47356021-89153480-d6f5-11e8-93b7-a3f4cc7e9a58.png">

**Comment by omar20261** [comment]
@emurgobot claim

**Comment by omar20261** [comment]
@emurgobot done
