### ISSUE TITLE
problem: "resources" wording not updated everywhere

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/cardanoupdate#229]
problem: `social resources` has been renamed to `community` but there are still legacy wording problems.

<img width="767" alt="screenshot 2018-10-24 at 12 04 26 pm" src="https://user-images.githubusercontent.com/8143945/47405636-1bb0e480-d785-11e8-98ab-e518f668d4f6.png">
<img width="306" alt="screenshot 2018-10-24 at 12 04 15 pm" src="https://user-images.githubusercontent.com/8143945/47405637-1bb0e480-d785-11e8-86f9-5425030161a1.png">
<img width="349" alt="screenshot 2018-10-24 at 12 04 08 pm" src="https://user-images.githubusercontent.com/8143945/47405638-1bb0e480-d785-11e8-9f60-4220ab55af48.png">

**Comment by geekyd** [comment]
@emurgobot claim

**Comment by gazhayes** [comment]
@geekyd good to see you here again :)

**Comment by geekyd** [comment]
@gazhayes Thanks. Same here :)
