### ISSUE TITLE
problem: not clear to users how active the site is

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/cardanoupdate#230]
problem: it's not clear to users how active the site is, the more active it looks the more likely they are to add their own stuff.

solution: change the "new comments this month" to reflect *all* new content in the last 30 days. Comments on *everything* as well as the number of new items themselves.

SyncedCron should be used to generate this number every x minutes otherwise this will create too many db reads.

ping @anbud this is probably for you

**Comment by anbud** [comment]
Done in #233.

@emurgobot done
