### ISSUE TITLE
problem: not easy to embed youtube videos in "learn" content

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/cardanoupdate#234]
problem: not easy to embed youtube videos in "learn" content

solution: simplest is probably to just add a `embed a video` thing under the content form and add it to the content detail/display page.

**Comment by omar20261** [comment]
@emurgobot claim

**Comment by omar20261** [comment]
@gazhayes after testing .. I think it's easy to embed youtube videos
can you tell me what exactly bother you about it ?

**Comment by gazhayes** [comment]
Oh ok, let me check and reply :)

**Comment by gazhayes** [comment]
@omar20261 can you create some test content and embed one on the production server?

**Comment by omar20261** [comment]
give me the link please ..
this is test on local (the image)
![screenshot from 2018-10-25 12-50-53](https://user-images.githubusercontent.com/21290723/47495519-a7de0d00-d854-11e8-8418-32314d23c8b2.png)

just copy the embed code and paste it into the content field .. super easy

**Comment by gazhayes** [comment]
Ah yeah ok. 

This is too difficult for normal users, it needs to be as easy as facebook.

I guess we could generate the embed code from a youtube link or something and insert it. 

Any other ideas?

**Comment by anbud** [comment]
We can maybe add a 'embed video' button to the editor toolbar which would present users with a modal where they could enter the YouTube video link. That should be quite easy for users, I believe. :)

**Comment by gazhayes** [comment]
Yeah, @anbud you wanna do it?

**Comment by anbud** [comment]
Sure thing.

@emurgobot claim

**Comment by anbud** [comment]
Done in #240.

@emurgobot done
