### ISSUE TITLE
problem: Node#moveTo was deprecated. Use Container#append.

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/cardanoupdate#25]
problem: when building and deploying with node, I get this CSS warning:
`Node#moveTo was deprecated. Use Container#append.`

**Comment by MadanBhandari** [comment]
Any way to reproduce this error on development ?

**Comment by Chicooz** [comment]
I Investigated this issue and it seem like a famous meteor issue, not related to cardanoupdate.
