### ISSUE TITLE
Problem: Users can add the same tags to a resource multiple times

### ISSUE THREAD

**Issue by porcellus** [EmurgoHK/cardanoupdate#255]
Solution: disable the related buttons on UI and deduplicate the tag array after normalization before submitting

**Comment by porcellus** [comment]
@emurgobot claim

**Comment by geekyd** [comment]
@porcellus This will be done in https://github.com/EmurgoHK/cardanoupdate/issues/252

**Comment by porcellus** [comment]
I thought that was about multiple tags getting added to the DB with the same name.

**Comment by geekyd** [comment]
@porcellus You take care of the UI in this. 
I will take care of the DB in #252. :)

**Comment by porcellus** [comment]
ok

**Comment by porcellus** [comment]
@emurgobot done in #259
