### ISSUE TITLE
Problem: Wrong username used in codebase

### ISSUE THREAD

**Issue by anbud** [EmurgoHK/cardanoupdate#26]
Problem: I've used `user.username` in most places for the username, yet username is saved at `user.profile.name` now.

Solution: Update the codebase to reflect new changes.

**Comment by anbud** [comment]
@emurgobot claim

**Comment by anbud** [comment]
Done in #27.

@emurgobot done

**Comment by MadanBhandari** [comment]
@anbud username is required to be unique for user ?

**Comment by anbud** [comment]
Nope, it doesn't have to be unique at all.
