### ISSUE TITLE
problem: type of community is not displayed

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/cardanoupdate#265]
problem: communities can be added, but the type of community is not displayed to the end user.

solution: wherever possible, look at the uri and guess the community type (facebook, twitter, etc). Telegram uses the t.me/sdfadfs format. This should probably be done with a synced cron job.

Instead of the globe icon, use the appropriate social icon where applicable.
Telegram: https://fontawesome.com/icons/telegram?style=brands
facebook: https://fontawesome.com/icons/facebook-square?style=brands
twitter: https://fontawesome.com/icons/twitter-square?style=brands

**Comment by porcellus** [comment]
@emurgobot claim

**Comment by porcellus** [comment]
My proposal is to store the guessed type at creation and update at edits. A synced cron job could be useful for migration.

**Comment by porcellus** [comment]
@emurgobot done in #301
