### ISSUE TITLE
problem: flagging button looks dangerous

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/cardanoupdate#266]
problem: the icon used to flag content makes it look like it's a warning about the content. This is a universal problem across the whole site.

For example:
<img width="967" alt="screenshot 2018-10-29 at 12 13 36 pm" src="https://user-images.githubusercontent.com/8143945/47629097-26e48580-db74-11e8-85e7-ba1a93da864d.png">

solution: replace the icon in the UI with a dropdown and put a 'report' link in there (kind of like facebook).

These elipses seem to be the standard UI thing to use for dropdowns on content: https://fontawesome.com/icons/ellipsis-h?style=solid

**Comment by MadanBhandari** [comment]
@emurgobot claim

**Comment by MadanBhandari** [comment]
@emurgobot done in #275
