### ISSUE TITLE
problem: inconsistent uppercase in `add new` modal

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/cardanoupdate#268]
problem:
<img width="461" alt="screenshot 2018-10-29 at 12 19 03 pm" src="https://user-images.githubusercontent.com/8143945/47629239-f94c0c00-db74-11e8-84c7-046ab5a596ad.png">

**Comment by MadanBhandari** [comment]
@emurgobot claim

**Comment by MadanBhandari** [comment]
@emurgobot done in #274
