### ISSUE TITLE
problem: can't search from home route

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/cardanoupdate#270]
problem: can't search from home route

**Comment by AshHimself** [comment]
@emurgobot claim

**Comment by AshHimself** [comment]
@gazhayes - are you wanting a search in the header to just search projects? or everything? papers, events etc.

**Comment by gazhayes** [comment]
Definitely global search on the home route, i guess that could just be deployed site wide and filter it by projects/events/whatever on the appropriate routes

**Comment by AshHimself** [comment]
Yeh roger that mate.. i'll have a PR inbound shortly on this. oi @emurgobot do not unclaim me.

**Comment by AshHimself** [comment]
First pass done, still need to add filters.

Fixed in #412
@emurgobot label "done"
@emurgobot done
