### ISSUE TITLE
problem: adding dates and times to events is really annoying

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/cardanoupdate#272]
problem: adding dates and times to events is really annoying

solution: I really don't know, hopefully someone has some ideas

**Comment by MadanBhandari** [comment]
We can use some date range selector plugin with nice UI.

Check this out : http://www.daterangepicker.com/#examples

**Comment by MadanBhandari** [comment]
I am adding [this plugin](http://www.daterangepicker.com/#example2) for date range picker, let's see how it goes.

@emurgobot claim

**Comment by gazhayes** [comment]
Yeah that looks like it will be much better

**Comment by MadanBhandari** [comment]
@emurgobot done in #319
