### ISSUE TITLE
problem: no summary for learning resources

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/cardanoupdate#276]
problem: it's not clear what each learning resource is about.

<img width="1053" alt="screenshot 2018-10-29 at 3 06 21 pm" src="https://user-images.githubusercontent.com/8143945/47634349-37085f00-db8c-11e8-9e20-0037b5f4d144.png">

solution: add a summary field to learning resources and display this on the item's tile. This must be retroactively available on stuff that already exists in the database (users must be able to add the summary to items that were created before the pull request to solve this issue).

**Comment by MadanBhandari** [comment]
@emurgobot done in #280
