### ISSUE TITLE
problem: 'warnings' section isn't very clear

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/cardanoupdate#277]
problem: people are indicating that 'warnings' doesn't mean much to them and they aren't sure what it's for.

solution: change 'warnings' to 'scams'. Ensure that all related stuff in the UI is updated with this new word.

**Comment by MadanBhandari** [comment]
@emurgobot claim

**Comment by MadanBhandari** [comment]
@gazhayes do I need to update urls as well ?

**Comment by MadanBhandari** [comment]
@emurgobot done in #300
