### ISSUE TITLE
 Problem: Displayed columns in Homepage are odd

### ISSUE THREAD

**Issue by FC369** [EmurgoHK/cardanoupdate#279]
Displayed columns in homepage was 5 columns, user felt odd when browsing as seems there was one column missing 

<img width="1021" alt="1029-ux-only-5-columns" src="https://user-images.githubusercontent.com/44566386/47638777-848bc880-db9a-11e8-80af-e80ebeae6391.png">

**Comment by MadanBhandari** [comment]
This is because in home route, there is limit for 5 items, making this limit to 6 should fix this.

**Comment by MadanBhandari** [comment]
@emurgobot claim

**Comment by MadanBhandari** [comment]
@emurgobot done in #291
