### ISSUE TITLE
Problem: Not enough wordcounts for Title

### ISSUE THREAD

**Issue by FC369** [EmurgoHK/cardanoupdate#281]
"Title" of content was over limited, which is not enough to name content specifically.

<img width="691" alt="1029-ux-title-limited-words" src="https://user-images.githubusercontent.com/44566386/47639046-50fd6e00-db9b-11e8-9499-939562973468.png">

**Comment by gazhayes** [comment]
Let's go to 90 characters and see what happens.

**Comment by MadanBhandari** [comment]
@emurgobot claim

I'll send single PR for this and #285

**Comment by MadanBhandari** [comment]
@emurgobot done in #288
