### ISSUE TITLE
Problem: Icon for missing source code is cumbersome

### ISSUE THREAD

**Issue by FC369** [EmurgoHK/cardanoupdate#289]
problem: this icon is redundant/confusing with the github icon.

<img width="689" alt="1029-ux- -no-need-remark-missing link-non-opensource" src="https://user-images.githubusercontent.com/44566386/47643160-8eff8f80-dba5-11e8-92cb-5f9b68b84a25.png">

<img width="878" alt="1029-ux- -no-need-remark-missing link-non-opensource-2" src="https://user-images.githubusercontent.com/44566386/47643188-a50d5000-dba5-11e8-92b0-f094cfb1ff45.png">

**Comment by gazhayes** [comment]
I suggest that the best solution is as follows:

When there's no source repository, remove the github icon from the card and use a github icon with a red line through it instead. The help modal can stay the same then. Adding a github repo can be done through the item's detail page (users probably aren't going to be adding this data point from the home route or the projects route anyway).

I'll make an icon in photoshop now and put it up here.

**Comment by gazhayes** [comment]
![nogithub](https://user-images.githubusercontent.com/8143945/47645724-d2113100-dbac-11e8-8e1a-44a5ff725256.png)
![nogithub-300px](https://user-images.githubusercontent.com/8143945/47645725-d2113100-dbac-11e8-84c8-27d386fd4965.png)

**Comment by MadanBhandari** [comment]
@emurgobot claim

**Comment by MadanBhandari** [comment]
@emurgobot done in #303
