### ISSUE TITLE
In Project section comment posted by name not display.

### ISSUE THREAD

**Issue by higunjan** [EmurgoHK/cardanoupdate#293]
@gazhayes 
Problem: Project posted by No name display

![cardano](https://user-images.githubusercontent.com/6925531/47645970-7dfc5180-db98-11e8-9e07-d312765205c2.png)

**Comment by MadanBhandari** [comment]
I believe this is the same issue as #222

**Comment by higunjan** [comment]
Need to resolve of find another one ?

**Comment by MadanBhandari** [comment]
You can start working on any unclaimed issues (or new). If you believe both the issue are same, close this one and claim #222 and start working.

**Comment by gazhayes** [comment]
Yeah the root problem here is #222, fixing that will fix this one. I'll close this now.
