### ISSUE TITLE
problem: cannot upload PDFs when adding Research items

### ISSUE THREAD

**Issue by higunjan** [EmurgoHK/cardanoupdate#294]
I found issues in Upload APIs I think, Not sure 
Research > New Research paper > PDF allow only
Problem : When I try to upload .pdf file then show me error like " Internal server error ".

![pdf upload issues found](https://user-images.githubusercontent.com/6925531/47646452-fa436480-db99-11e8-8f82-0e03a03ec836.png)

I found issues from back-end side related to path.

**Comment by gazhayes** [comment]
@higunjan I updated the problem statement to make it C4 compliant.

**Comment by gazhayes** [comment]
This is working on production, it's just your local file paths (so it's not actually a problem). If it was on production, it would be a valid problem.

**Comment by gunjan-bvi** [comment]
@gazhayes True. You provided the static path in code, so I assume on production it will be static even. 

Except you, someone else tried in the different system then in other systems you've to change everywhere in API's file where you've written.
