### ISSUE TITLE
problem: missing source code handling is inconsistent

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/cardanoupdate#312]
problem: missing source code handling is not clear

This problem should be read in reference to #289 

This is now redundant:
<img width="322" alt="screenshot 2018-10-30 at 9 59 41 am" src="https://user-images.githubusercontent.com/8143945/47690866-bfd5d800-dc2a-11e8-8952-9662b7e4e5d4.png">

The "no github" icon should trigger this modal instead of the "add repository" modal:
<img width="542" alt="screenshot 2018-10-30 at 10 00 45 am" src="https://user-images.githubusercontent.com/8143945/47690861-bfd5d800-dc2a-11e8-8368-d598b0dc9d65.png">

This modal should only be triggered on the project detail page, add an "add source repository" link to trigger it.
<img width="535" alt="screenshot 2018-10-30 at 10 00 30 am" src="https://user-images.githubusercontent.com/8143945/47690863-bfd5d800-dc2a-11e8-896d-1b07f9639518.png">

On the home route this hasn't been updated (it's probably better if we don't duplicate code for stuff like this):
<img width="327" alt="screenshot 2018-10-30 at 10 03 58 am" src="https://user-images.githubusercontent.com/8143945/47690953-31158b00-dc2b-11e8-9527-520a4df068c4.png">

The project detail page hasn't been updated either:
<img width="930" alt="screenshot 2018-10-30 at 10 06 03 am" src="https://user-images.githubusercontent.com/8143945/47691025-79cd4400-dc2b-11e8-8c26-42d93e25ea39.png">

**Comment by porcellus** [comment]
@emurgobot claim

**Comment by porcellus** [comment]
@emurgobot done in #333
