### ISSUE TITLE
problem: no description for each section

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/cardanoupdate#313]
problem: users might be a bit confused about what each section is actually for.

solution: add a description to each section.

projects: 
`Projects that are built on or for Cardano. This includes everything from developer libraries to user wallets.`

events:
`Any Cardano related events, anywhere in the world.`

research:
`Peer reviewed academic papers that are related to Cardano`

scams:
`Scam websites, wallets etc. Anything that people should be wary about.`

Learn:
`From basic introductions to developer documentation.`

Community:
`Telegram groups, meetup groups, facebook groups, forums, etc.`

**Comment by MadanBhandari** [comment]
@emurgobot claim

**Comment by MadanBhandari** [comment]
@gazhayes do this needs to be added on home route as well ?

**Comment by MadanBhandari** [comment]
@emurgobot done in #328
