### ISSUE TITLE
Problem: Confusing usage of 'Eye' icon

### ISSUE THREAD

**Issue by FC369** [EmurgoHK/cardanoupdate#323]
This icon only available in "event" 

User doesn't know what will happen when it is "watched", eg: where watched items were stored

<img width="1307" alt="1030-ux-cofusing-eye-icon" src="https://user-images.githubusercontent.com/44566386/47701883-3d630d80-dc56-11e8-831b-c1951410480a.png">

**Comment by MadanBhandari** [comment]
Or we can add follow button, I think follow would make more sense on this for everyone instead of eye icon or watch/unwatch

**Comment by MadanBhandari** [comment]
@emurgobot claim

**Comment by MadanBhandari** [comment]
@emurgobot done in #364
