### ISSUE TITLE
Problem: "Event" RVSP link isn't active

### ISSUE THREAD

**Issue by FC369** [EmurgoHK/cardanoupdate#325]
The link appeared as text but not an active link to the website, which is not convenient 

<img width="1328" alt="1030-ux-rvsp-link-not-working-1" src="https://user-images.githubusercontent.com/44566386/47702476-fb3acb80-dc57-11e8-9f92-123727d3f9ec.png">

**Comment by MadanBhandari** [comment]
@emurgobot claim

**Comment by MadanBhandari** [comment]
@emurgobot done in #329
