### ISSUE TITLE
Problem: "Event" location link is not active

### ISSUE THREAD

**Issue by FC369** [EmurgoHK/cardanoupdate#326]
The location shown as text only, not directly to google map

<img width="966" alt="1030-ux-location-link-not-working" src="https://user-images.githubusercontent.com/44566386/47702673-a9467580-dc58-11e8-9fc7-f15723446852.png">

**Comment by MadanBhandari** [comment]
@emurgobot 
I will send single PR for this and #325

**Comment by MadanBhandari** [comment]
@emurgobot claim

**Comment by MadanBhandari** [comment]
@emurgobot done in #329
