### ISSUE TITLE
Problem: No date filtering for Project/Research search bar 

### ISSUE THREAD

**Issue by FC369** [EmurgoHK/cardanoupdate#327]
eg: search by latest date/oldest date, for user to find content easier

<img width="1272" alt="1030-ux-search-bar-filtering" src="https://user-images.githubusercontent.com/44566386/47702940-7cdf2900-dc59-11e8-8bac-5ebcdaaa1ead.png">

**Comment by porcellus** [comment]
@emurgobot claim

**Comment by porcellus** [comment]
@emurgobot done in #345
