### ISSUE TITLE
problem: missing assets when direct loading some pages

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/cardanoupdate#331]
problem: when going to some pages directly instead of following a link, some assets are missing (e.g. the header image).

Here's an example of https://cardanoupdate.space/events/benjamin-soong-ledger-best-security-practices-for-institutional-investors

<img width="1494" alt="screenshot 2018-10-30 at 4 26 59 pm" src="https://user-images.githubusercontent.com/8143945/47705150-a485bf80-dc60-11e8-88a1-50db3f22a3e8.png">

**Comment by MadanBhandari** [comment]
@emurgobot claim

**Comment by MadanBhandari** [comment]
@emurgobot done in #332
