### ISSUE TITLE
problem: user cannot remove tags in edit mode

### ISSUE THREAD

**Issue by geekyd** [EmurgoHK/cardanoupdate#338]
problem: user cannot remove tags in edit mode

![screenshot 2018-10-30 at 3 11 17 pm](https://user-images.githubusercontent.com/12807846/47709350-160c4080-dc56-11e8-93ae-d59d53438133.png)

solution: show already added tags in the field & allow users to remove them

**Comment by geekyd** [comment]
@emurgobot claim

**Comment by anbud** [comment]
Hmm, this one was working last time I checked yesterday. When you're there, add some WDIO (UI) tests if possible, as I believe the tagging system is not tested so regressions occur. :)

**Comment by geekyd** [comment]
@anbud I will be adding tests for the select2 in a separate issue. :)

**Comment by geekyd** [comment]
Done in #376 

@emurgobot done
