### ISSUE TITLE
problem: add new button is out of place

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/cardanoupdate#370]
problem: add new button is out of place

solution: move the button to the top-right of the title bar on desktop and make the button full width on mobile (but put it *below* the statistics box)

**Comment by MadanBhandari** [comment]
@emurgobot claim

**Comment by MadanBhandari** [comment]
@gazhayes You mean just above view all on desktop ?

**Comment by MadanBhandari** [comment]
@emurgobot done in #379
