### ISSUE TITLE
Problem: Limited words count in abstract

### ISSUE THREAD

**Issue by cathfung** [EmurgoHK/cardanoupdate#373]
current allowance is not enough 
<img width="880" alt="1031-ux-research-abstract-words-number" src="https://user-images.githubusercontent.com/44600923/47776898-6ce54900-dd2e-11e8-88b7-794204c847d0.png">

**Comment by MadanBhandari** [comment]
@gazhayes Do we need limit at all [on research abstract and project description] ? I would suggest remove limits on everything except headline and summary.

**Comment by gazhayes** [comment]
@MadanBhandari yeah I tend to agree. We can limit it later if it becomes a problem. The only thing I'm worried about is some kind of overflow vulnerability with mongodb so maybe *some* limit is needed but it can be massively big and not shown to the user.

**Comment by MadanBhandari** [comment]
@emurgobot done in #391
