### ISSUE TITLE
Problem: Research paper source link is missing 

### ISSUE THREAD

**Issue by cathfung** [EmurgoHK/cardanoupdate#377]
There was no link can be put in the content, and user can't dig deeper(link of university published paper) of the content directly

<img width="1103" alt="1031-ux-research-source-link" src="https://user-images.githubusercontent.com/44600923/47777253-4d025500-dd2f-11e8-993d-9407fe4be22c.png">

**Comment by porcellus** [comment]
@emurgobot claim

**Comment by porcellus** [comment]
Should we provide a way to add extra links or a way to embed them in the text?

**Comment by porcellus** [comment]
I propose adding multiple links that would be shown like (and next to) "Download PDF"

**Comment by gazhayes** [comment]
Yeah  agree. Multiple links are the simplest solution.

**Comment by porcellus** [comment]
@emurgobot done in #415
