### ISSUE TITLE
Duplicate Project name.

### ISSUE THREAD

**Issue by higunjan** [EmurgoHK/cardanoupdate#384]
@gazhayes Is it possible to have duplicate project name. Two different project have same name.
Please mention comment over here, If error then comment or else close it.

![duplicate project name](https://user-images.githubusercontent.com/6925531/47790794-1aac2400-dd3e-11e8-8a89-687e71cbdd68.png)

**Comment by gazhayes** [comment]
Not really a problem yet, let's see what heppens when users start doing things . Also, please read the C4
