### ISSUE TITLE
Problem: The shown words of title & description is too limited 

### ISSUE THREAD

**Issue by cathfung** [EmurgoHK/cardanoupdate#387]
problem: the title is not completely shown, and description limited too much, user can't get what it trying to say

<img width="1126" alt="1101-words-too-limited" src="https://user-images.githubusercontent.com/44600923/47831507-c780b280-ddcb-11e8-8739-1864cb1d0cde.png">

solution: display the full heading. This might make the layout weird, but we could use https://codepen.io/andybarefoot/pen/QMeZda or masonry to display it nicely.

**Comment by gazhayes** [comment]
whoever does this might want to do #388 at the same time

**Comment by MadanBhandari** [comment]
@gazhayes do we need settings icon (add and edit) separately ? I was thinking about add this to ellipsis (with report link).

@emurgobot claim

**Comment by gazhayes** [comment]
I think put it all under the elipses

**Comment by MadanBhandari** [comment]
@gazhayes One more question : Do we need report link on own item (when user can edit and delete) ?

**Comment by gazhayes** [comment]
hmmm actually if currentuser we dont need to show report anyway, and if not currentuser dont need to show edit

**Comment by MadanBhandari** [comment]
@emurgobot done in #399
