### ISSUE TITLE
problem: weird titles shown in search result page

### ISSUE THREAD

**Issue by cathfung** [EmurgoHK/cardanoupdate#389]
after search words were input, these titles shown below search bar and it's weird

oh i get it, it try to categorize the content but seems weird and not obvious

<img width="827" alt="1101-weird-titles-shown" src="https://user-images.githubusercontent.com/44600923/47831673-7e7d2e00-ddcc-11e8-9623-3096abc0a008.png">

**Comment by MadanBhandari** [comment]
@cathfung  I am not getting this, in which page you are searching ?

**Comment by porcellus** [comment]
This is the tag search page, I assume.

**Comment by anbud** [comment]
Indeed, it is the tag page. A simple if should do the trick.

**Comment by porcellus** [comment]
@emurgobot claim

**Comment by porcellus** [comment]
Yeah, sorry:) 
@emurgobot done #420
