### ISSUE TITLE
problem: weird menu layout on mobile

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/cardanoupdate#394]
problem: weird menu layout on mobile, kind of looks like a double menu.

solution: **on mobile** remove the menu with background image, users will probably know to use the side menu

<img width="425" alt="screenshot 2018-11-01 at 4 20 53 pm" src="https://user-images.githubusercontent.com/8143945/47840757-556f9400-ddf2-11e8-87d0-04a621fb3e1e.png">

**Comment by gazhayes** [comment]
Oh I mean really remove the whole thing, including the menus. Since people will probably just use the side menu on mobile anyway

**Comment by MadanBhandari** [comment]
Got it :)
@emurgobot claim

**Comment by MadanBhandari** [comment]
@emurgobot done in #401
