### ISSUE TITLE
problem: no active class on side menu

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/cardanoupdate#397]
problem: no active class on side menu so when a user is on any specific route the side menu doesn't stay highlighted.

<img width="1454" alt="screenshot 2018-11-01 at 6 03 37 pm" src="https://user-images.githubusercontent.com/8143945/47845622-7ccd5d80-de00-11e8-8fa7-1363c9107894.png">

solution: use active class or whatever to keep the menu items highlighted in same color as onhover

<img width="1460" alt="screenshot 2018-11-01 at 6 02 04 pm" src="https://user-images.githubusercontent.com/8143945/47845585-61625280-de00-11e8-801d-afa7e31b49bc.png">

**Comment by porcellus** [comment]
@emurgobot claim

**Comment by porcellus** [comment]
@emurgobot done in #419

**Comment by porcellus** [comment]
Currently, it adds the active class if the route is currently active: it's not the same as the hover state but this seems to be more standard.
As a side note: the route doesn't stay active if the user enters into viewing/editing an item. This can be changed easily though.
