### ISSUE TITLE
problem: moderator and user status not shown on profile

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/cardanoupdate#400]
problem: moderator status is not shown on users profile, and neither is the user's ranking 

In this example, Cath Fung is a moderator, and this is shown on her name when she posts content:
<img width="471" alt="screenshot 2018-11-01 at 6 31 46 pm" src="https://user-images.githubusercontent.com/8143945/47846899-7640e500-de04-11e8-8558-58d0f5e0763d.png">

But there's nothing on her profile page. Should probably add something like `{{name}} is a moderator.`
<img width="698" alt="screenshot 2018-11-01 at 6 31 37 pm" src="https://user-images.githubusercontent.com/8143945/47846898-7640e500-de04-11e8-8394-25072783aabb.png">

While doing that,  may as well add the user's ranking too (for all users). This should be displayed as something like `ranking: 7 out of 22 users, based on comments and contributions`:
<img width="654" alt="screenshot 2018-11-01 at 6 30 03 pm" src="https://user-images.githubusercontent.com/8143945/47846840-41349280-de04-11e8-8aad-08da315f236f.png">

**Comment by MadanBhandari** [comment]
@emurgobot claim

**Comment by MadanBhandari** [comment]
@gazhayes I am not getting mod data for ranking. Is this only available for Moderators ? Which PR should check for this ?

**Comment by anbud** [comment]
Huh, that was one of my PRs. It's calculated only for the top 10% of the users. It's calculated somewhere in imports/api/users/methods.js, I believe.

**Comment by MadanBhandari** [comment]
@emurgobot done in #426
