### ISSUE TITLE
problem: "new" button takes up too much space

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/cardanoupdate#402]
problem: "new" button on home route takes up too much space (a whole row) on desktop sized screens.

<img width="1012" alt="screenshot 2018-11-01 at 6 44 20 pm" src="https://user-images.githubusercontent.com/8143945/47847496-61fde780-de06-11e8-8d6f-64c88d2bc8a1.png">

solution: not totally sure but I think what could be done is to reduce the size of the statistic boxes and make a "Add new stuff" button or whatever on the same line (to the right of the stats boxes) in a style that blends in somehow.

on small screens this is *not* a problem and it should remain the way it is (full width button).

**Comment by MadanBhandari** [comment]
@gazhayes What about adding this as a first box [contents not stats] on home route ? Like we have bid cta on BlockRazor, and we are using masonry layout, sizing shouldn't be the problem here, I guess.

**Comment by gazhayes** [comment]
Yeah that was also on my mind. Whatever you think looks better ;)

**Comment by MadanBhandari** [comment]
@emurgobot claim

**Comment by MadanBhandari** [comment]
@emurgobot done in #427
