### ISSUE TITLE
Problem: Content is out of "research" box

### ISSUE THREAD

**Issue by cathfung** [EmurgoHK/cardanoupdate#404]
<img width="791" alt="1101-error-appears-in-research" src="https://user-images.githubusercontent.com/44600923/47847973-cf5e4800-de07-11e8-8086-79fb6c19f6a0.png">

**Comment by MadanBhandari** [comment]
@emurgobot claim

Not a big task, I'll send PR for this on priority.

**Comment by MadanBhandari** [comment]
@emurgobot done in #409
