### ISSUE TITLE
problem: cards are cluttered

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/cardanoupdate#406]
problem: cards are cluttered, there's not enough spacing.

<img width="340" alt="screenshot 2018-11-01 at 7 03 25 pm" src="https://user-images.githubusercontent.com/8143945/47848317-f49f8600-de08-11e8-9e6e-e85b67393fb8.png">

solution: add a bit more space

**Comment by MadanBhandari** [comment]
@emurgobot done in #409
