### ISSUE TITLE
Problem: [New Research] Upload PDF button rotating after error

### ISSUE THREAD

**Issue by akatrodiya** [EmurgoHK/cardanoupdate#410]
Problem: [New Research] Upload PDF button rotating after error comes and Upload button showing 'Uploading'

Solution: Reset Upload button state after action perform and give response

**Comment by anbud** [comment]
While you're there, you can fix it for image uploads as well. If I remember correctly, it's in the same place (imports/ui/shared/uploader), or it's even handled by the same code. :)

**Comment by higunjan** [comment]
@emurgobot claim

**Comment by higunjan** [comment]
@emurgobot done
