### ISSUE TITLE
Problem: [Forms] Field required message is not hide after enter value

### ISSUE THREAD

**Issue by akatrodiya** [EmurgoHK/cardanoupdate#411]
Problem: when we try to add new entry using form, if required fields are missing/no content it gives warning under particular input, then if we enter value in input, error message is still there.

Solution: Update validation with enter value in input, update/remove error/warning message

**Comment by MadanBhandari** [comment]
@emurgobot claim

**Comment by MadanBhandari** [comment]
@emurgobot done in #429
