### ISSUE TITLE
problem: searched keyword was not highlighted 

### ISSUE THREAD

**Issue by cathfung** [EmurgoHK/cardanoupdate#413]
after the keyword was input in the top search bar, nothing was highlighted in the result so  user can't locate the keyword

<img width="1427" alt="1101-search-bar-no-highlighted" src="https://user-images.githubusercontent.com/44600923/47859751-f0d02b80-de29-11e8-8c77-38d7d5e2e22b.png">

**Comment by omar20261** [comment]
@emurgobot claim

**Comment by omar20261** [comment]
@emurgobot done
