### ISSUE TITLE
problem: event time zone can easily be incorrect

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/cardanoupdate#443]
problem: event time zone can easily be incorrect

solution: store event times in unix time. When calculating the unix time, take the timezone into consideration. This should not be taken from the user's browser because they might be creating it from somewhere else. It should be taken from the event location. I'm not sure the simplest way to deal with this but hopefully someone will have some ideas.

**Comment by anbud** [comment]
@emurgobot claim

**Comment by anbud** [comment]
Done in #456.

@emurgobot done
