### ISSUE TITLE
problem: "copy and paste" text doesn't work for searchbar

### ISSUE THREAD

**Issue by cathfung** [EmurgoHK/cardanoupdate#445]
when user pasted  text on the search bar, nothing happens for the search bar
 it only works  when user input text manually 

<img width="1017" alt="1105-copy and paste doesn t work for searchbar" src="https://user-images.githubusercontent.com/44600923/47979743-8f48df00-e0ff-11e8-981e-5c506fb47d35.png">

**Comment by porcellus** [comment]
@emurgobot claim

**Comment by porcellus** [comment]
@emurgobot done in #469
