### ISSUE TITLE
problem: extra bar for breadcrumbs is clumsy

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/cardanoupdate#448]
problem: extra bar for breadcrumbs is clumsy and takes up heaps of space.

possible solution:
Breadcrumbs aren't really important on the home route or the other top-level routes like /projects etc since there are headings etc. The place where they are really important is on the detail view of each item. The bar could be removed and the breadcrumbs could be put here (screenshot):

<img width="1677" alt="screenshot 2018-11-05 at 4 31 30 pm" src="https://user-images.githubusercontent.com/8143945/47986662-5832f780-e118-11e8-9abf-1d300c31acb5.png">

**Comment by higunjan** [comment]
@emurgobot claim

**Comment by higunjan** [comment]
@emurgobot done
