### ISSUE TITLE
problem: confused symbol for Moderator scores

### ISSUE THREAD

**Issue by cathfung** [EmurgoHK/cardanoupdate#449]
it feels like a negative number at a glance

<img width="931" alt="1105-negative-symbol-moderator" src="https://user-images.githubusercontent.com/44600923/47994143-63901e00-e12c-11e8-8454-e71d08955803.png">

**Comment by MadanBhandari** [comment]
@emurgobot claim

**Comment by MadanBhandari** [comment]
@emurgobot done in #452
