### ISSUE TITLE
Problem: Moderator > Flagged items, If reported from scams then not working

### ISSUE THREAD

**Issue by higunjan** [EmurgoHK/cardanoupdate#453]
Problem: Moderator > Flagged items, If reported from scams then not working.

Soultions: Need to update link ternary operator in file `imports/ui/pages/moderator/flagged/flaggeditems.js line:85` 

Replace  ```(i.summary ? `/warnings/${i.slug}`)``` with ```(i.summary ? `/scams/${i.slug}`)```

@MadanBhandari Please claim and update repo.

![moderator flagged item href](https://user-images.githubusercontent.com/6925531/47997481-fecfc600-e121-11e8-8e82-695057e72d26.png)

**Comment by MadanBhandari** [comment]
@emurgobot claim

**Comment by MadanBhandari** [comment]
@emurgobot done in #454
