### ISSUE TITLE
problem: number of comments not shown

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/cardanoupdate#46]
problem: number of comments not shown

There are a number of comments under this news item but the UX is not updated to reflect this.

<img width="1009" alt="screen shot 2018-10-04 at 1 51 27 pm" src="https://user-images.githubusercontent.com/8143945/46455239-b0ef3780-c7dc-11e8-944f-a50649ef1d02.png">

**Comment by geekyd** [comment]
@emurgobot claim

**Comment by geekyd** [comment]
Fixed in #62 
@emurgobot done
