### ISSUE TITLE
problem: breadcrumb UI is weird

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/cardanoupdate#460]
problem: breadcrumbs look weird as a UL item, the location also takes up a lot of space.

<img width="209" alt="screenshot 2018-11-06 at 11 48 35 am" src="https://user-images.githubusercontent.com/8143945/48041809-ec08d000-e1b9-11e8-9ad2-3495db011b87.png">

solution: remove UL and **_significantly_** reduce the amount of space used.

**Comment by higunjan** [comment]
@emurgobot claim

**Comment by higunjan** [comment]
@emurgobot done
