### ISSUE TITLE
problem: "view" used in breadcrumbs

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/cardanoupdate#461]
problem: "view" used in breadcrumbs instead of the item name

<img width="735" alt="screenshot 2018-11-06 at 11 51 41 am" src="https://user-images.githubusercontent.com/8143945/48041936-6a657200-e1ba-11e8-9f81-0cc85e62ea87.png">

related: #460

**Comment by higunjan** [comment]
@emurgobot claim

**Comment by gazhayes** [comment]
related: #463

**Comment by higunjan** [comment]
@MadanBhandari I checked `route.js` they're we can change but we found slug over there, is there any sort way we can update over there, Need your suggestions.

**Comment by MadanBhandari** [comment]
As slugs are unique for each post, find post headline by slug should work

**Comment by higunjan** [comment]
@emurgobot done
