### ISSUE TITLE
problem: google maps API credentials not fetched from mongo

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/cardanoupdate#465]
problem: google maps API credentials not fetched from mongo

solution: make use of the `config` collection used in #458 

ping @anbud I'm not sure if you actually did this already and I just can't find it.

**Comment by anbud** [comment]
I'll do it.

@emurgobot claim

**Comment by anbud** [comment]
Done in #480.

Add a record like this to the `Config` collection:
```
{ 
    "_id" : "google-maps-api", 
    "key" : "AIzaSyBdA0LxFu54uNoygxxxxxxxxxxxx"
}
```

Also, change the `_id` of the recaptcha config to `recaptcha`, or add a new record with this _id if you can't modify it. It should look like this:
```
{ 
    "_id" : "recaptcha", 
    "publicKey" : "6LerhE8UAAAAAxxxxx_xxxxxx", 
    "privateKey" : "6LerhE8UAAAAxxxxxxxxxx_xxxxxx"
}
```

@emurgobot done

**Comment by gazhayes** [comment]
FYI @anbud done
