### ISSUE TITLE
problem: font size of "about" title in profile is smaller than content

### ISSUE THREAD

**Issue by cathfung** [EmurgoHK/cardanoupdate#472]
it is smaller than the content of "about" which doesn't make sense 
<img width="490" alt="1106-font-size-profile-about" src="https://user-images.githubusercontent.com/44600923/48058433-5ee16d80-e1f1-11e8-928a-2ea70b2de0f6.png">

**Comment by MadanBhandari** [comment]
@emurgobot claim

**Comment by MadanBhandari** [comment]
@emurgobot done in #481
