### ISSUE TITLE
problem: tests running before merging is annoying

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/cardanoupdate#476]
problem: tests running before merging is annoying

solution: run tests on merge instead of on pull request. When using Jenkins we can just use a webhook on merge instead of on PR, but I'm not sure if this is possible with travis when using it as a github module. Ping @anbud for ideas

**Comment by anbud** [comment]
Hmm, currently it runs tests both on PR and on merge. I'll see if PR tests can be disabled, it should be possible.

@emurgobot claim

**Comment by anbud** [comment]
@gazhayes, I've disabled builds on PRs on every repo, tests will only run after successfull merges now.

@emurgobot done
