### ISSUE TITLE
problem: missing details on user profile

### ISSUE THREAD

**Issue by geekyd** [EmurgoHK/cardanoupdate#477]
problem: missing details on user profile.

solution: Add details about learning resource, research paper, community & events created user

**Comment by geekyd** [comment]
@emurgobot claim

**Comment by geekyd** [comment]
Done in #479 

@emurgobot done

**Comment by MadanBhandari** [comment]
I was working on same issue on #467 

@geekyd please check existing open issues, before creating an new issue in future.
