### ISSUE TITLE
problem: sort option in dropdown is clunky UX

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/cardanoupdate#48]
problem: sort option in dropdown is clunky UX

solution: I hope someone with better UX ideas than with me will think of something cool

**Comment by MadanBhandari** [comment]
@emurgobot label "UI-UX"
@emurgobot claim

I am exploring some ides, feel free to share your ides

ping @gazhayes @samuelralak

**Comment by MadanBhandari** [comment]
I kind of liked this, what you say about similar approach ?
![flipkart-sort](https://user-images.githubusercontent.com/6429311/46489629-8c6a7e00-c823-11e8-93a1-0ceb5d84c3a0.png)

I am thinking about Sort by : Newest, Oldest, Most Popular or Best Rated (I don't see Worst rested should be there :D)

ping @gazhayes @anbud @samuelralak

**Comment by MadanBhandari** [comment]
Done in #61 
@emurgobot done
