### ISSUE TITLE
problem: title of research paper too limited 

### ISSUE THREAD

**Issue by cathfung** [EmurgoHK/cardanoupdate#486]
not extra characters allowed  for official title 
<img width="563" alt="screen shot 2018-11-07 at 4 56 22 pm" src="https://user-images.githubusercontent.com/44600923/48120879-59962880-e2ae-11e8-98db-7231de87473a.png">

**Comment by anbud** [comment]
@emurgobot claim

**Comment by anbud** [comment]
Done in #489.

@emurgobot done
