### ISSUE TITLE
problem: users cannot add a profile picture

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/cardanoupdate#49]
problem: users cannot add a profile picture

solution: copy from blockrazor

**Comment by anbud** [comment]
@emurgobot claim

I'll reuse the uploader from Emurgis, I believe it's better there. Just one question, what upload directory should I use? (`/home/gareth/?_assets/static/images/`?)

**Comment by gazhayes** [comment]
Ah yeah I'm attempting to make this a pretty standard structure, so just replace `emurgis` with `cardanoupdate` as you'd suspect.

**Comment by anbud** [comment]
Done in #57.

@emurgobot done
