### ISSUE TITLE
Problem: upload doesn't work in development or tests

### ISSUE THREAD

**Issue by porcellus** [EmurgoHK/cardanoupdate#509]
The only way to make it work is to edit a file that could break prod if it was accidentally committed.
Solution: in development, the files should be saved in a location inside the repo that is ignored by git (and served by Meteor under the same paths as it is in prod)

**Comment by higunjan** [comment]
@porcellus True, It will break if someone accidentally committed and path is static inside `imports/api/uploader/method.js` no dynamic path exist there. 
Related to #294 .
Possible solutions: 
1) Make It dynamic path Inside folder.
2) add these file into .gitignored 
3) If you don't want to change path than, while merging code `moderator` have to double check these things.
@gazhayes / @MadanBhandari Request to pour your suggestion over here.

**Comment by gazhayes** [comment]
For now the simplest solution is to not test uploads. In development it should only be a problem if someone is doing something with uploads, if that's the case they might want to do something about it if it causes them enough of  a problem, but right now I don't see  this as a problem that's worth fixing.

**Comment by porcellus** [comment]
Ok, I'll close this then. It caused me problems when I was testing/working researchForm. The tests are already in place, I was just seeing what was causing it to fail on my pc.
(disregard the referencing commit, it was a typo)

**Comment by porcellus** [comment]
I suggest reopening this, today I almost committed my local fix which I needed to test adding researches. The problem is easily solvable by using an os provided tmpdir in development and the currently set path in production.
