### ISSUE TITLE
problem: side menu doesn't work on mobile

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/cardanoupdate#51]
problem: side menu doesn't work on mobile

can anyone else reproduce?

**Comment by MadanBhandari** [comment]
Yes, same for me, Not working. I am looking into this.

**Comment by anbud** [comment]
Not working for me as well.

**Comment by MadanBhandari** [comment]
@emurgobot claim

**Comment by MadanBhandari** [comment]
Done in #77 
@emurgobot done
