### ISSUE TITLE
problem: logo too big on mobile

### ISSUE THREAD

**Issue by AshHimself** [EmurgoHK/cardanoupdate#523]
problem:  logo is too big on mobile

solution: only show the image and not text on mobile to open up realestate.

**Comment by AshHimself** [comment]
@emurgobot claim

**Comment by gazhayes** [comment]
@AshHimself you still on this one?

**Comment by AshHimself** [comment]
Forgot to send PR, its done.. inbound shortly.

**Comment by AshHimself** [comment]
Fixed in #543
@emurgobot label "done"
@emurgobot done
