### ISSUE TITLE
Problem: search-bar cross not working, when search from header top-right side

### ISSUE THREAD

**Issue by higunjan** [EmurgoHK/cardanoupdate#528]
Problem: search-bar cross not working, when search from header top-right side.
![cross on search not working](https://user-images.githubusercontent.com/6925531/48415580-c3fa0d80-e773-11e8-8f2a-4e87b4a76b22.png)

Solution: Need to check `/search` and if any type is not exist then move to `home` page.

**Comment by higunjan** [comment]
@emurgobot claim

**Comment by higunjan** [comment]
@emurgobot claim

**Comment by higunjan** [comment]
@emurgobot claim

**Comment by higunjan** [comment]
@emurgobot claim

**Comment by higunjan** [comment]
@emurgobot label "claim"

**Comment by higunjan** [comment]
@emurgobot done

**Comment by MadanBhandari** [comment]
@higunjan looks like @emurgobot is down, issue is already logged, follow [this issue](https://github.com/EmurgoHK/emurgobot/issues/18) for further updates.

**Comment by gazhayes** [comment]
emurgobot is down, I'll fix it when I wake up
