### ISSUE TITLE
Problem: [Home] '+ Add new content' popup gives error and no redirect to login

### ISSUE THREAD

**Issue by akatrodiya** [EmurgoHK/cardanoupdate#530]
Problem:  '+ Add new content' popup gives error and no redirect to login, when user is not logged in

Solution: import package, and fix redirect issue.

**Comment by akatrodiya** [comment]
@emurgobot claim

**Comment by higunjan** [comment]
@akatrodiya Can you please add snapshot, It's working well in my local and even on production too.
Please check on `https://cardanoupdate.space`

**Comment by akatrodiya** [comment]
![error](https://user-images.githubusercontent.com/15026463/48416765-112bae80-e777-11e8-9673-6de11ab0f76c.png)
Error in https://cardanoupdate.space as well

**Comment by higunjan** [comment]
@akatrodiya No need to import package, package already imported which is in `Meteor.isClient` condition. [ File : `startup/both/route.js` ]. You've to import outside the conditions.
But
I think `notify` would not work in `route.js` I think not sure. @MadanBhandari please pour your thoughts.

**Comment by akatrodiya** [comment]
@emurgobot done in #531
