### ISSUE TITLE
problem: something weird going on with user rankings

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/cardanoupdate#533]
problem: something weird going on with user rankings - two users are ranked as 1/33 (see screenshots).

<img width="573" alt="screenshot 2018-11-14 at 3 16 51 pm" src="https://user-images.githubusercontent.com/8143945/48466325-7daeb800-e820-11e8-88c2-4f91ffd2b190.png">
<img width="622" alt="screenshot 2018-11-14 at 3 16 27 pm" src="https://user-images.githubusercontent.com/8143945/48466327-7daeb800-e820-11e8-8941-3b1891cc387a.png">

**Comment by akatrodiya** [comment]
@emurgobot done in #537
