### ISSUE TITLE
problem: not clear what all code is doing

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/cardanoupdate#542]
problem: it's not clear what all code is doing, some things are quite difficult to understand and _reason about_.

solution: everyone please comment more before you push a commit :)

There should be a comment at least every 2-3 lines describing what your code is doing (and why).

I know it's sometimes boring but if other people cannot understand what your code is doing when they're half asleep on monday morning after an alcohol fuelled weekend then it's a bad commit.

ping @higunjan @AshHimself @porcellus @samuelralak @MadanBhandari @anbud @geekyd

**Comment by AshHimself** [comment]
As someone who has alcohol fueled weekends often I am all for this and an abuser of not writing comments as often as I should :) please call me out when I don't.
