### ISSUE TITLE
Problem: search not working proper

### ISSUE THREAD

**Issue by higunjan** [EmurgoHK/cardanoupdate#547]
Problem: search bar not working proper, like, 
- If user enter white-space then result header capitalise.
- If enter any text in search-bar then result is fine but after text hit space bar then show all result which is wrong.

Solution: Need to `trim` search text any how.

**Comment by higunjan** [comment]
@emurgobot claim

**Comment by gazhayes** [comment]
hey @higunjan also have a look at the Emurpas repository for new problems.

**Comment by higunjan** [comment]
@gazhayes Sure once these done I'll check that too.

**Comment by higunjan** [comment]
@emurgobot done
