### ISSUE TITLE
problem: sorting by popularity isn't meaningful

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/cardanoupdate#55]
problem: sorting by popularity isn't meaningful because the oldest entries will have more time to gain more votes.

solution: copy blockrazor's comment voting metrics (or reimpliment something similar if that's simpler). The general idea is:
rating = (upvotes - downvotes) / total number of votes

#54 is related

**Comment by samuelralak** [comment]
@emurgobot claim

**Comment by samuelralak** [comment]
@emurgobot done

done in #115
