### ISSUE TITLE
problem: security vulnerability found

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/cardanoupdate#569]
problem: 
![screenshot 2018-11-22 at 4 22 09 pm](https://user-images.githubusercontent.com/8143945/48890140-efb37c80-ee72-11e8-8924-803ebc83d5f8.png)

**Comment by porcellus** [comment]
As there are no patched versions we can't really fix this ourselves (besides fixing it in a fork and sending a PR). What we could do is to move over to another library, e.g.: editor.md. We can implement something like this example https://pandao.github.io/editor.md/examples/custom-toolbar.html

**Comment by anbud** [comment]
Hmm, looking at the simplemde repo, it seems abandoned. Maybe we should migrate to editor.md.

But, there's another, simpler fix to this one. [This](https://github.com/sparksuite/simplemde-markdown-editor/issues/721#issuecomment-439303763) comment says that adding `sanitize: true` to our markdown processor should fix the given problem.

**Comment by gazhayes** [comment]
It's up to you guys, both look about equally simple solutions. If you think it's a worthwhile project just fork it under emurgohk and apply the C4 to it, I have a quick guide here: http://socialarchitecture.science/forking-an-open-source-repository/ (skip to the part about forking).

**Comment by porcellus** [comment]
I don't think it's worthwhile (at least not because of this). I'll test if sanitize fixes it and migrate to editor.md otherwise. 
@emurgobot claim

**Comment by porcellus** [comment]
It worked, good catch @anbud 
@emurgobot done in #574
