### ISSUE TITLE
Problem: language chooser is too big

### ISSUE THREAD

**Issue by porcellus** [EmurgoHK/cardanoupdate#581]
It can break the mobile layout:
![image](https://user-images.githubusercontent.com/1129990/48920251-1041fd80-ee98-11e8-9263-583a351f12c7.png)
Also, it's placed weirdly on desktops:
![image](https://user-images.githubusercontent.com/1129990/48920269-323b8000-ee98-11e8-9120-c36eccb777fa.png)
Solution: it should be smaller, and placed between the GitHub and notification icons (there is too much space between them anyway) or next to the username/login button

**Comment by porcellus** [comment]
@emurgobot claim

**Comment by porcellus** [comment]
I think we would be better served by a footer as it's done in blockrazor and recommended by https://usersnap.com/blog/design-language-switch/

**Comment by porcellus** [comment]
@emurgobot done in #582

**Comment by anbud** [comment]
You’re right, putting it in the footer it’s better.
