### ISSUE TITLE
Problem: language switcher is hard to find

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/cardanoupdate#601]
Problem: language switcher is hard to find

solution: add an additional language switcher to the username dropdown and the top of the side menu.

<img width="235" alt="screenshot 2018-11-29 at 10 11 49 am" src="https://user-images.githubusercontent.com/8143945/49194744-4105c380-f3bf-11e8-95e3-b53d4cbef249.png">
<img width="266" alt="screenshot 2018-11-29 at 10 11 45 am" src="https://user-images.githubusercontent.com/8143945/49194745-4105c380-f3bf-11e8-8539-2d8290224db1.png">

**Comment by geekyd** [comment]
@emurgobot claim

**Comment by geekyd** [comment]
Done in #602 

@emurgobot done
