### ISSUE TITLE
problem: users can't actually add new languages to system

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/cardanoupdate#629]
problem: users can't actually add new languages or new translations of menu items etc. For example, if I want to add Japanese, it's not actually possible.

<img width="564" alt="screenshot 2018-12-04 at 10 29 29 am" src="https://user-images.githubusercontent.com/8143945/49414788-953de880-f7af-11e8-91c1-89c2467d7d6c.png">

ping @anbud

**Comment by anbud** [comment]
@emurgobot claim

**Comment by anbud** [comment]
Done in #630.

@emurgobot done

**Comment by anbud** [comment]
It represents the scope of the translation (e.g. comments, projects, etc).

Is the PWD env variable set correctly in the production environment? It should be set to project root so translations files could be fetched from the file system. It doesn't have to be PWD, I've just used it as it's used by default. It populates correctly in the development environment.
