### ISSUE TITLE
Problem : potential security vulnerabilities in dependencies

### ISSUE THREAD

**Issue by MadanBhandari** [EmurgoHK/cardanoupdate#645]
Problem : potential security vulnerabilities in dependencies

More details [here](https://github.com/EmurgoHK/cardanoupdate/network/alerts).

Solution : Update vulnerable dependencies.

**Comment by MadanBhandari** [comment]
@emurgobot claim

**Comment by MadanBhandari** [comment]
The security vulnerability is on package `https-proxy-agent` which is dependency of [deprecated package github](https://www.npmjs.com/package/github) and this is dependency of `git-commit-push-via-github-api`.

Any idea, how to resolve this kind of issue ? Or we can use another package instead of `git-commit-push-via-github-api`.

ping @anbud @gazhayes

**Comment by gazhayes** [comment]
Ah ok that's for the language thing.

One round-about solution to this would be to just store all language pairs in mongo instead of in the codebase. @anbud how much work do you think is in that, just to know what this last resort looks like (it would solve a couple of other undocumented problems I noticed).

**Comment by gazhayes** [comment]
@MadanBhandari I took you off this one for now till we have more info, but feel free to claim it again if you want to solve it.

**Comment by gazhayes** [comment]
ping @anbud any ideas for this one?

**Comment by anbud** [comment]
Hmm, we could save everything in mongo, it shouldn’t be too much work, but I do have to check if tapi18n supports mongo translations out of the box. If it doesn’t, it’ll be harder to implement.

But, it would be harder to add translations. Now it’s as easy as editing a file, if we switch to mongo, we could use the existing UI for adding translations, but we could maybe allow moderators to add translations without reviews or something.

**Comment by porcellus** [comment]
@emurgobot claim It looks like we can update or use alternatives for these issues

**Comment by porcellus** [comment]
@emurgobot done in #774
