### ISSUE TITLE
problem: activity looks boring

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/cardanoupdate#650]
problem: the activity metrics (see image) look quite inactive and and might discourage new users.

solution: instead of showing total users, new users, and new content this month, change it to display the total number of items in common categories (I guess projects, research, and learning resources).

Should probably change the colours to match the categories too.

**Comment by MadanBhandari** [comment]
@emurgobot claim

**Comment by gazhayes** [comment]
Madan while you're there, you should probably use a synced cron (already used elsewhere) to populate the numbers into some collection that's already used on the home route. If we check these values on each load it will make mongo cry.

If that doesn't make sense let me know and I'll explain in more detail ;)

**Comment by MadanBhandari** [comment]
> If that doesn't make sense let me know and I'll explain in more detail ;)

Yes, please :)
