### ISSUE TITLE
Problem : Welcome email is too boring

### ISSUE THREAD

**Issue by MadanBhandari** [EmurgoHK/cardanoupdate#657]
Problem : Welcome email is too boring

Solution : Make welcome email little bit interesting add some content (and banner maybe ?).

Current Email : 

![verify-email](https://user-images.githubusercontent.com/6429311/50572689-4ce40b80-0deb-11e9-8397-78e37be930eb.png)

ping @gazhayes for content and ideas

**Comment by gazhayes** [comment]
@madanbhandari sure, if you feel like making it nicer, go ahead ;)

I don't really know but a banner or something would be fun.

**Comment by MadanBhandari** [comment]
@emurgobot claim

**Comment by MadanBhandari** [comment]
Currently I have made this for email verification : 

![email-tmplate](https://user-images.githubusercontent.com/6429311/54379733-f67b2f00-46af-11e9-94dd-40dfaea3a2e8.png)

I'll send a PR in with templates for welcome email (after verification), password reset etc.

**Comment by MadanBhandari** [comment]
@emurgobot done in #762
