### ISSUE TITLE
problem: layout with images is clunky

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/cardanoupdate#68]
problem: layout with images is clunky

solution: force images to be scaled to an appropriate size (but maintain ratio). Take the largest dimension from width and height and render the image at (for example) 200px width or height while leaving the other side to auto scale and preserve the original ratio.

**Comment by MadanBhandari** [comment]
For this we can force max-height, and give width auto, them image will maintain aspect radio with fixed height.

@emurgobot claim

**Comment by MadanBhandari** [comment]
Q : How can I upload images in local ? 

ping @gazhayes @anbud

**Comment by anbud** [comment]
First, you'll have to create a directory for image uploads:
```
sudo mkdir -p /home/gareth/cardanoupdate_assets/static/images/
sudo chmod -R 777 /home/gareth/cardanoupdate_assets/static/images/
```
then, if you want to see them on the site in local:
```
sudo ln -s /home/gareth/cardanoupdate_assets/static/images ./public/images
```
in the root of Meteor project.

It should do the trick, at least it did for me on local.

**Comment by MadanBhandari** [comment]
@anbud I got it, it's working now. Thank you :)

One more question : `/public/images` should be ignored on git push right ?

**Comment by anbud** [comment]
Yap, it should be ignored.  `/images` in production are served from a separate node server if I remember correctly.

**Comment by MadanBhandari** [comment]
Done in #78 

@emurgobot done
