### ISSUE TITLE
problem: verification emails not being sent

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/cardanoupdate#711]
problem: verification emails not being sent

solution: first step is to check the current codebase to see what we need to add to support this, and then select a free email provider thing to actually send messages in a way that won't be caught by spam filters.

**Comment by MadanBhandari** [comment]
@gazhayes 

It's working as expected on local, can you check the `MAIL_URL` on production ?

**Comment by gazhayes** [comment]
Hmmm ok I will check. What did you set it to locally?

**Comment by MadanBhandari** [comment]
@gazhayes 

`
MAIL_URL=smtp://user:pass@smtp.sendgrid.net:587
`
UserID : blockrazor
Password : blockrazor125

**Comment by gazhayes** [comment]
Thanks, deleted and saved, I'll set the config when I wake up :)
