### ISSUE TITLE
problem: sorting by negative rating is not needed

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/cardanoupdate#72]
problem: sorting by negative rating is not needed

solution: remove the negative rating sort link, and remove the arrow from the remaining rating sort link.

<img width="511" alt="screen shot 2018-10-05 at 11 23 34 am" src="https://user-images.githubusercontent.com/8143945/46514586-595ed380-c891-11e8-860d-221bd5e73ba5.png">

**Comment by MadanBhandari** [comment]
@emurgobot claim

**Comment by MadanBhandari** [comment]
Done in #75 
@emurgobot done
