### ISSUE TITLE
Problem: [Notification] no need to show it until user not log in

### ISSUE THREAD

**Issue by akatrodiya** [EmurgoHK/cardanoupdate#766]
Problem: [Notification] Notifications display there if userId is match, so need to show it
![Screenshot 2019-03-16 at 2 11 03 PM](https://user-images.githubusercontent.com/15026463/54472891-419f5a00-47f6-11e9-9571-8c7117e02f9f.png)

Solution: if user not logged in then hide icon in header

**Comment by akatrodiya** [comment]
@emurgobot claim

**Comment by MadanBhandari** [comment]
Hey @akatrodiya , If this is about on top navigation, this should be fixed in #767

**Comment by akatrodiya** [comment]
It is about top navigation + page. So, I will do some fixes there.

**Comment by akatrodiya** [comment]
@emurgobot done in #769
