### ISSUE TITLE
Problem: items cannot be deprecated

### ISSUE THREAD

**Issue by vantuz-subhuman** [EmurgoHK/cardanoupdate#772]
Hi! Wanted to report "Guardians of Cardano" community entry, because this coalition is dead now, but there are only two options: "spam" or "scam":

![image](https://user-images.githubusercontent.com/5585355/54876328-1bde0a80-4e1f-11e9-9836-dd3c9518b524.png)

There's gotta be another option like "This is incorrect" with maybe a field to send a link to some source, proving incorrectness. Or just a general option "Other reason" with a comment field.

**Comment by gazhayes** [comment]
Yeah I think the simplest solution to this is to allow an option to add a "This no longer exists".

Ping @porcellus @samuelralak @anbud @geekyd @MadanBhandari @akatrodiya

**Comment by MadanBhandari** [comment]
@emurgobot claim

**Comment by MadanBhandari** [comment]
@emurgobot done in #777

**Comment by gazhayes** [comment]
@vantuz-subhuman FYI it's now solved in production :)
