### ISSUE TITLE
Problem: [Header] top links icon color not change, not redirect on icon

### ISSUE THREAD

**Issue by akatrodiya** [EmurgoHK/cardanoupdate#809]
Problem: [Header] top links icon color not change, not redirect on icon
![Screenshot 2019-04-22 at 7 34 09 PM](https://user-images.githubusercontent.com/15026463/56504320-c8ea9680-6535-11e9-9dd8-0f1c33a0f12f.png)

Solution: Set link color on mouse over, also icon+text should be redirect to page

**Comment by akatrodiya** [comment]
@emurgobot claim

**Comment by gazhayes** [comment]
Hey Ajay, just wondering, are you also missing the sidebar?

**Comment by akatrodiya** [comment]
you mean sidebar should be there for desktop?

**Comment by akatrodiya** [comment]
@emurgobot done in #811
