### ISSUE TITLE
Problem : Home page shows only news

### ISSUE THREAD

**Issue by MadanBhandari** [EmurgoHK/cardanoupdate#82]
Problem : Home page shows only news

Solution : 

Add top or recent news and projects only, for complete list add individual link for each (news and projects)
OR
Add projects as well on list give user options to show only news or only projects or both

ping @gazhayes

**Comment by MadanBhandari** [comment]
@emurgobot claim

**Comment by MadanBhandari** [comment]
Guys, I am little bit confused on this. There is very few content for now.

What I wanted to do is make a list of all news and projects but there is no voting on projects for sorting to work.

any suggestions @gazhayes @anbud @samuelralak

**Comment by samuelralak** [comment]
The home page currently shows news items, IMHO we can leave it like that for now and allow it to evolve as more content is added- the C4 should guide. Am honestly not certain if we would want to 
mix the News Updates with the Projects as at now. This is just my take.

Though if you have any ideas of making the home page look better, well, feel free to play around.

**Comment by MadanBhandari** [comment]
> Though if you have any ideas of making the home page look better, well, feel free to play around.

Yap, that's why I created #84 , I am trying show the overview of project in home page itself :D 

I am thinking about keeping news items on one main column and projects on another (only few projects or main projects), It's more of a UX and design stuff than just coding. Sometimes I loved this type of work, where I don't just code but do a little research on user experience, design standards and common practices. Wish me luck :D

**Comment by MadanBhandari** [comment]
Done in #87 
@emurgobot done
