### ISSUE TITLE
problem: image in news card is too large

### ISSUE THREAD

**Issue by samuelralak** [EmurgoHK/cardanoupdate#86]
problem: the image in the news card is too large making actual content appear squeezed.

solution: reduce size of image in news card and center it

**Comment by samuelralak** [comment]
@emurgobot claim

**Comment by MadanBhandari** [comment]
Actually this is related to #84, can you just wait for me to that complete, if you haven't started working on this ?

**Comment by samuelralak** [comment]
ok

@emurgobot unclaim
