### ISSUE TITLE
problem: projects without github repo can be dangerous

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/cardanoupdate#94]
problem: projects which do not have a github repo can be dangerous because the community cannot peer review the codebase. In blockchain, it's generally only scams that are not open source.

solution: when a project is added without a github repository, add a warning icon along with the other icons at the bottom of the card. When clicked, this should launch a modal with a warning that no source repository has been added.

**Comment by geekyd** [comment]
@emurgobot claim
